using System.IO;
using System.Linq;
using System.Net;
using System.Xml.Linq;
using System.Windows;
using APILib;

namespace FloorLayout
{
    public partial class ViewModelCanvas
    {
        /// <summary>
        /// Send a FloorLayoutInput tag to the API to convert it to a FloorLayout tag
        /// </summary>
        /// <param name="ele"></param>
        /// <returns></returns>
        public XElement GetFloorLayout(XElement ele)
        {
            XElement result;

            // Log the input
            DebugWindow.WriteLine("FloorLayoutInput XML:");
            // Count input elements
            var outlineHoles = ele.Descendants("outline").Descendants("hole").Count();
            var openAreaHoles = ele.Descendants("openarea").Descendants("hole").Count();
            var wallSegments = ele.Descendants("wallsegmentarray").Descendants("linesegment").Count();
            DebugWindow.WriteLine($"  - Outline holes: {outlineHoles}");
            DebugWindow.WriteLine($"  - Open area holes: {openAreaHoles}");
            DebugWindow.WriteLine($"  - Wall segments: {wallSegments}");
            DebugWindow.WriteLine("");

            // Call APILib directly instead of web API
            DebugWindow.WriteLine("Calling API.APIEntry('getfloorlayout')...");
            API api = new API();
            APIStatus status = api.APIEntry("getfloorlayout", ele.ToString());

            // Check API status
            DebugWindow.WriteLine($"API Status: {(status.Success ? "SUCCESS" : "FAILED")}");
            if (!string.IsNullOrEmpty(status.ErrorMessage))
            {
                DebugWindow.WriteLine($"  Error: {status.ErrorMessage}");
            }
            if (!string.IsNullOrEmpty(status.OutputFile))
            {
                DebugWindow.WriteLine($"  Output file: {status.OutputFile}");
            }

            if (!status.Success)
            {
                string error = $"GetFloorLayout failed: {status.ErrorMessage}";
                DebugWindow.WriteLine($"ERROR: {error}");
                MessageBox.Show(error, "API Error", MessageBoxButton.OK, MessageBoxImage.Error);
                throw new System.Exception(error);
            }

            // The API writes the result to a temp file, load it
            if (!string.IsNullOrEmpty(status.OutputFile) && File.Exists(status.OutputFile))
            {
                FileInfo fi = new FileInfo(status.OutputFile);
                DebugWindow.WriteLine($"Loading FloorMaker XML from temp file ({fi.Length} bytes)...");

                result = XElement.Load(status.OutputFile);

                // Check if result has any rooms
                var vertexList = result.Descendants("list")
                    .FirstOrDefault(x => x.Attribute("name")?.Value == "vertexlist");
                var edgeList = result.Descendants("list")
                    .FirstOrDefault(x => x.Attribute("name")?.Value == "edgelist");
                var roomList = result.Descendants("list")
                    .FirstOrDefault(x => x.Attribute("name")?.Value == "assembledroomlist");

                int vertexCount = vertexList?.Elements("vertex").Count() ?? 0;
                int edgeCount = edgeList?.Elements().Count() ?? 0;
                int roomCount = roomList?.Elements().Count() ?? 0;

                DebugWindow.WriteLine("");
                DebugWindow.WriteLine("RoomGenWrapper output:");
                DebugWindow.WriteLine($"  - Vertices: {vertexCount}");
                DebugWindow.WriteLine($"  - Edges: {edgeCount}");
                DebugWindow.WriteLine($"  - Rooms: {roomCount}");

                if (roomCount > 0)
                {
                    MessageBox.Show($"FloorLayout generated successfully with {roomCount} rooms",
                        "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                }
                else
                {
                    DebugWindow.WriteLine("");
                    DebugWindow.WriteLine("WARNING: No rooms were generated by RoomGenWrapper!");
                    MessageBox.Show("WARNING: No rooms were generated. Check that you have defined outlines, open areas, and walls.",
                        "Warning", MessageBoxButton.OK, MessageBoxImage.Warning);
                }
            }
            else
            {
                string error = $"GetFloorLayout did not produce an output file. OutputFile={status.OutputFile ?? "null"}";
                DebugWindow.WriteLine($"ERROR: {error}");
                MessageBox.Show(error, "API Error", MessageBoxButton.OK, MessageBoxImage.Error);
                throw new System.Exception(error);
            }

            return result;

#if false
            // OLD CODE - called web API
            string url;

            // Step 2. Retrieve XML descriptions of the Simple Panels based on these descriptions
            url = "http://www.meshola.com/API/APIAlpha";

            using (WebClient client = new WebClient())
            {
                /*
                 * Get the mesh of connected panels
                 */
                var reqparm = new System.Collections.Specialized.NameValueCollection();
                reqparm.Add("command", "getfloorlayout");
                reqparm.Add("xmldata", ele.ToString());

                byte[] responsebytes = client.UploadValues(url, "POST", reqparm);
                MemoryStream ms = new MemoryStream(responsebytes);

                result = XElement.Load(ms);

            }

            return result;
#endif
        }

    }
}
